title: "Jeewoong Derm Lab"
url: "https://jwchoi-derm-lab.github.io"
repository: "jwchoi-derm-lab/jwchoi-derm-lab.github.io"

author:
  name: "Jeewoong (Jiwoong) Choi, MD, PhD"
  avatar: "/images/profile.jpg"  # 사진을 images 폴더에 넣고 경로 지정
  bio: "Dermatologic Surgeon & Computational Biologist"
  location: "Suwon & Seongnam, South Korea"
  employer: "Ajou University School of Medicine"
  uri: "https://www.ajoumc.or.kr/medicineEn/univ/profView.do?deptTp=&deptNo=65&no=660"
  email: "jwchoi@ajou.ac.kr"
  github: "jwchoi-derm-lab"
  googlescholar: "YOUR_GOOGLE_SCHOLAR_ID"  # 구글스칼라 ID 있을 경우 입력
